// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: setting.sql

package sql

import (
	"context"
)

const getAllSetting = `-- name: GetAllSetting :many
select key, value, description from setting
`

func (q *Queries) GetAllSetting(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.Query(ctx, getAllSetting)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Value, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
