basePath: /
definitions:
  middleware.AuthUserData:
    properties:
      id:
        type: integer
      name:
        type: string
      role:
        $ref: '#/definitions/sql.UserRole'
      status:
        $ref: '#/definitions/sql.UserStatus'
      username:
        type: string
    type: object
  request.AuthLoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  response.BaseMetadataPagination:
    properties:
      page:
        type: integer
      per_page:
        type: integer
      total:
        type: integer
    type: object
  response.BaseResponse:
    properties:
      code:
        example: 999
        type: integer
      data: {}
      message:
        example: Message!
        type: string
    type: object
  response.BaseResponsePagination-response_EntryHistory:
    properties:
      content:
        items:
          $ref: '#/definitions/response.EntryHistory'
        type: array
      metadata:
        $ref: '#/definitions/response.BaseMetadataPagination'
    type: object
  response.EntryHistory:
    properties:
      date:
        type: string
      id:
        type: string
      location_code:
        type: string
      type:
        type: string
      vehicle_number:
        type: string
      vehicle_type_code:
        type: string
    type: object
  sql.UserRole:
    enum:
    - admin
    - karyawan
    type: string
    x-enum-varnames:
    - UserRoleAdmin
    - UserRoleKaryawan
  sql.UserStatus:
    enum:
    - active
    - banned
    type: string
    x-enum-varnames:
    - UserStatusActive
    - UserStatusBanned
info:
  contact:
    email: rizal.arfiyan.23@gmail.com
    name: Rizal Arfiyan
    url: https://rizalrfiyan.com
  description: This is a API documentation of BE Park Ease
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: BE Park Ease API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Base Home
      operationId: get-base-home
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Get Base Home based on parameter
      tags:
      - home
  /auth/login:
    post:
      consumes:
      - application/json
      description: Auth Login
      operationId: post-auth-login
      parameters:
      - description: Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AuthLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Post Auth Login based on parameter
      tags:
      - auth
  /auth/me:
    get:
      consumes:
      - application/json
      description: Auth Me
      operationId: get-auth-me
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/middleware.AuthUserData'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseResponse'
      security:
      - AccessToken: []
      summary: Get Auth Me based on parameter
      tags:
      - auth
  /history/entry:
    get:
      consumes:
      - application/json
      description: All History
      operationId: get-all-history
      parameters:
      - default: 1
        description: Page
        in: query
        name: page
        type: integer
      - default: 10
        description: Limit
        in: query
        name: limit
        type: integer
      - description: Search
        in: query
        name: search
        type: string
      - description: Order by
        enum:
        - id
        - location_code
        - vehicle_type_code
        - vehicle_number
        - date
        - type
        in: query
        name: order_by
        type: string
      - description: Order
        enum:
        - asc
        - desc
        in: query
        name: order
        type: string
      - description: Type
        enum:
        - entry
        - exit
        - fine
        in: query
        name: type
        type: string
      - description: Vehicle Type
        in: query
        name: vehicle_type
        type: string
      - description: Location
        in: query
        name: location
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.BaseResponsePagination-response_EntryHistory'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseResponse'
      security:
      - AccessToken: []
      summary: Get All History based on parameter
      tags:
      - history
securityDefinitions:
  AccessToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
